apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysmap-api
spec:
  selector:
    matchLabels:
      app: sysmap
  template:
    metadata:
      labels:
        app: sysmap
    spec:
      containers:
      - name: sysmap-api-container
        image: lucasliborio/sysmap-api:v1.1
        ports:
        - containerPort: 5050
        env:
        - name: MONGO_URL
          value: mongodb://mongodb-service/sys-social
        - name: RABBIT_URL
          value: amqp://my-release-rabbitmq
        - name: BUCKET_ENDPOINT
          value: http://my-minio:9000
        - name: JWT_SECRET
          value: somesecretfordev
        