# Deployment do MONGO
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-depl
  labels:
    app: mongodb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-depl
  template:
    metadata:
      labels:
        app: mongodb-depl
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
      restartPolicy: Always
        
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb-depl
  ports: 
  - port: 27017
    targetPort: 27017

---