export const users = [{
  username: 'Lucas',
  email: 'lucas@gmail.com',
  password: '123',
  passwordConfimation: '123'
}, {
  username: 'Amanda',
  email: 'amanda@gmail.com',
  password: '123',
  passwordConfimation: '123'
}, {
  username: 'Julia',
  email: 'julia@gmail.com',
  password: '123',
  passwordConfimation: '123'
}, {
  username: 'Monica',
  email: 'monica@gmail.com',
  password: '123',
  passwordConfimation: '123'
}, {
  username: 'fredeudinho',
  email: 'fred@gmail.com',
  password: '123',
  passwordConfimation: '123'
}, {
  username: 'bruno',
  email: 'bruno@gmail.com',
  password: '123',
  passwordConfimation: '123'
}, {
  username: 'leoonardo',
  email: 'leo@gmail.com',
  password: '123',
  passwordConfimation: '123'
}, {
  username: 'cintia',
  email: 'cintia@gmail.com',
  password: '123',
  passwordConfimation: '123'
},{
  username: 'Rosana',
  email: 'rosana@gmail.com',
  password: '123',
  passwordConfimation: '123'
}, {
  username: 'Junior',
  email: 'Junior@gmail.com',
  password: '123',
  passwordConfimation: '123'
}]
